apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: pillow
spec:
  memoryQuota: 6Gi
  replicas: 2
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno 
  enableFlush: true
  enableIndexReplica: true
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:6.5.0
  platform: aws
  serverGroups:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  cluster:
    clusterName: cb-example
    dataServiceMemoryQuota: 6Gi
    indexServiceMemoryQuota: 6Gi
  logging:
    logRetentionTime: 604800s
    logRetentionCount: 20
  servers:
  - size: 6
    name: data_services
    services:
    - data
    serverGroups:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
    resources:
      requests:
        cpu: "4"
        memory: 8Gi
      limits:
        cpu: "4"
        memory: 8Gi
  - size: 3
    name: index_services
    services:
    - index
    serverGroups:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
    resources:
      requests:
        cpu: "4"
        memory: 8Gi
      limits:
        cpu: "4"
        memory: 8Gi
  - size: 3
    name: query_services
    services:
    - query
    serverGroups:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
    resources:
      requests:
        cpu: "4"
        memory: 8Gi
      limits:
        cpu: "4"
        memory: 8Gi
